name: project2_test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter
        run:  make lint
      - name: Run tests
        run:  make test
      - name: Code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: 9045e46124f7dd49cad9a8cc8b57904594c45064781c5a739fa19cad0d339e73
        with:
          coverageCommand: make test-coverage
          debug: true
